### ISSUE TITLE
Unable to bulk delete with deleteRow request

### ISSUE THREAD

**Issue by daveskull81** [smartsheet-platform/smartsheet-javascript-sdk#3]
Making attempts to delete rows in bulk is failing for me. I have attempted by passing an array into the options for the delete request.
When using an array of Row Ids as the rowId parameter in the options for the delete request an error is given that it cannot be found.
Example error:
```
{ statusCode: 404, errorCode: 1006, message: 'Not Found' }
```
Example request:
```javascript
var deleteOptions = {
    sheetId: 8408753847461321,
    rowId: [4062292632461234, 8565892259831234] //Modified row and sheet ids for example
};

// Delete row.
smartsheet.sheets.deleteRow(deleteOptions)
    .then(function (data) {
        console.log(data);
    })
    .catch(function (error) {
        console.log(error);
    });
```
Only when passing in a single row Id does the request successfully go through.

**Comment by stmcallister** [comment]
Thanks for pointing out the bug, @daveskull81! I just pushed a fix.
