### ISSUE TITLE
Docs for getAttachment not right

### ISSUE THREAD

**Issue by dwightware4** [smartsheet-platform/smartsheet-javascript-sdk#4]
`smartsheet.sheets.getAttachment({id: sheetsId})` 

should be  
`smartsheet.sheets.getAttachment({sheetId: sheetsId, attachmentID: attachmentId})`

**Comment by kbrandl** [comment]
Thanks for pointing this out -- the sample code in this repo (ExampleUsage.md) has been updated per your suggestion. 

Also, FYI -- the Smartsheet API documentation contains example requests and responses for each operation.  For example: http://smartsheet-platform.github.io/api-docs/?javascript#get-attachment.  For the most part, I'd recommend leveraging the examples in the API docs whenever possible, as they're maintained more frequently than the examples in this repo (ExampleUsage.md).

**Comment by dwightware4** [comment]
Awesome thanks for that. I didn't even notice the code samples were
different.

Dwight Ware
