### ISSUE TITLE
GetSheet with filtered rows by column value

### ISSUE THREAD

**Issue by apeixoto** [smartsheet-platform/smartsheet-javascript-sdk#7]
Is there any way of getting the rows that match a value in a determined column?

For instance, I have this table:
Col1   | Col2   | Col3
a         | 1        | z
b         | 2        | w

I would like to call getSheet() method with some parameter like:
```
filters: [{
    columnId: 12412451251441234, //id for Col1
    type: "CUSTOM",
    criteria: {
        operator: "EQUAL",
        value1: "b"
    }
}]
```
It sould only return the second row...
Is there a way of doing this?

**Comment by activescott** [comment]
Not really. The REST API doesn't offer a way to do this type of operation the SDK. You could obviously pull down all the sheet rows and easily find the ones that meet such a criteria.
