### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by oleonides** [smartsheet-platform/smartsheet-javascript-sdk#82]
I'm trying to consume the API from a vue component and after installing the package and call a variable I got the following error
```
ERROR in ./node_modules/smartsheet/lib/utils/httpRequestor.js
Module not found: Error: Can't resolve 'fs'
```

how can I solve this issue?

**Comment by thomas-kreamer** [comment]
This looks like it's related to a known issue when working with Webpack and fs. Try adding the following to your webpack config:
`node: {
   fs: "empty"
}`

 More detail on this issue can be found [here](https://github.com/webpack-contrib/css-loader/issues/447) .
