### ISSUE TITLE
SDK does not support objectValue requests

### ISSUE THREAD

**Issue by TheRedstoneScientist** [smartsheet-platform/smartsheet-javascript-sdk#91]
According to the smartsheet API Docs, I should be able to use "level" parameter in my options to get a complex object for Multi-Contact columns. Unfortunately all I'm getting in return is value and displayValue. It appears the SDK does not support this yet.
```

var options = {
    id: SHEET_ID, //Id of sheet
    queryParameters = {
            include: ["objectValue"],
            level: 1
        }
}

ss.sheets.getSheet(options)
            .then(function (results) {
                console.log(results.rows[args[0]].cells[6])
            })
```
The above code returns:

{ columnId: 8746190272522116, displayValue: 'John Smith, Danny Doe' }

But according to the docs I would expect it to return a complex object.
If I try the same request via Postman I get the correct results.

**Comment by timwellswa** [comment]
I believe if you just drop the array notation you should get the desired outcome:
```
var options = {
    id: SHEET_ID,
    queryParameters: {
        include: "objectValue",
        level: 1,
    }
};
```

**Comment by timwellswa** [comment]
@TheRedstoneScientist I am going to close this as I believe this issue should be resolved for you. Feel free to reopen and ping me if you believe that is not the case.

**Comment by TheRedstoneScientist** [comment]
@timwellswa This is not resolved.
